### ISSUE TITLE
Proot alpine 'apk update' error

### ISSUE THREAD

**Issue by nicklamn** [Yonle/alpine-proot#4]
when i run alpine proot and run apk update or apk add bash etc, it says WARNING: updating and opening 'https://...'temporary error (try again later)

**Comment by Yonle** [comment]
Rerun the command again. It does not works at the first time. Or restart alpine proot

**Comment by nicklamn** [comment]
I have a fix. the '1.1.1.1' and '1.0.0.1' DNS servers do not work for me. I have fixed it by switching them to google DNS, by editing the /etc/resolv.conf file in the proot.
________________________________

**Comment by Yonle** [comment]
Fixed in the new commit.
